name: PD UI Stress Tests Windows
run-name: Podman Desktop E2E UI Stress Test (Windows)

on:
  schedule:
    - cron: '0 5 * * 1' #run every monday at 5AM
  workflow_dispatch:
    inputs:
      pd_repo_options:
        default: 'REPO=podman-desktop,FORK=podman-desktop,BRANCH=main'
        description: 'Podman Desktop Extension repo, fork and branch'
        type: string
        required: true
      npm_target:
        default: 'test:e2e:ui-stress'
        description: 'npm target to run tests'
        type: string
        required: true
      podman_remote_url:
        default: 'https://github.com/containers/podman/releases/download/v5.4.0/podman-5.4.0-setup.exe'
        description: 'podman latest released version exe'
        type: string
        required: true
      podman_options:
        default: 'INIT=1,START=1,ROOTFUL=0,NETWORKING=0'
        description: 'Podman machine configuration options, no spaces'
        type: 'string'
        required: true
      podman_provider:
        type: choice
        description: 'Podman virtualization provider, default is wsl, alternative hyperv'
        options:
        - wsl
        - hyperv
        required: true
      image_size:
        default: 'tiny'
        description: 'Image size to be used for generating podman objects'
        type: 'choice'
        options:
          - tiny
          - small
          - medium
          - large
        required: true
      env_vars:
        default: 'ELECTRON_ENABLE_INSPECT=true,OBJECT_NUM=100,KEEP_VIDEOS_ON_PASS=true,KEEP_TRACES_ON_PASS=true'
        description: 'Env. Variables passed into target machine, ie: VAR1=xxx,VAR2=true,VAR3=15,VAR4="Pass me along"'
        type: 'string'
        required: true
      mapt_params:
        description: |
          **Create instance (leave empty to use repo secrets/variables)**

          **Format:** IMAGE=xxx;VERSION_TAG=xxx;CPUS=xxx;MEMORY=xxx;EXCLUDED_REGIONS=xxx

          **Example:**
            IMAGE=quay.io/redhat-developer/mapt;VERSION_TAG=v0.9.8;CPUS=4;MEMORY=32;EXCLUDED_REGIONS="westindia,centralindia,southindia,australiacentral,australiacentral2,australiaeast,australiasoutheast,southafricanorth,southafricawest"
        required: false
        type: string
      images_version:
        default: 'BUILDER="v0.0.3",PODMAN="v0.0.3",RUNNER="v0.0.3"'
        description: 'Testing images versions, no spaces'
        type: 'string'
        required: true
      host_params: 
        default: 'CPUS="8",MEMORY="16"'
        description: Number of CPUs and GBs of memory, no spaces
        type: 'string'
        required: true
jobs:
  windows:
    name: ${{ matrix.windows-version }} - ${{ matrix.windows-featurepack }}
    timeout-minutes: 90
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        windows-version: ['11']
        windows-featurepack: ['24h2-ent']

    steps:
    - name: Set the default env. variables
      env:
        DEFAULT_NPM_TARGET: 'test:e2e:ui-stress'
        DEFAULT_PODMAN_PROVIDER: 'wsl'
        DEFAULT_PODMAN_OPTIONS: 'INIT=1,START=1,ROOTFUL=0,NETWORKING=0'
        DEFAULT_PD_REPO_OPTIONS: 'REPO=podman-desktop,FORK=podman-desktop,BRANCH=main'
        DEFAULT_HOST_PARAMS: 'CPUS="8",MEMORY="16"'
        DEFAULT_IMAGE_SIZE: 'tiny'
        DEFAULT_ENV_VARS: 'ELECTRON_ENABLE_INSPECT=true,OBJECT_NUM=100,KEEP_VIDEOS_ON_PASS=true,KEEP_TRACES_ON_PASS=true'
        DEFAULT_URL: 'https://api.cirrus-ci.com/v1/artifact/github/containers/podman/Artifacts/binary/podman-remote-release-windows_amd64.zip'
        DEFAULT_IMAGES_VERSIONS: 'BUILDER="v0.0.3",PODMAN="v0.0.3",RUNNER="v0.0.3"'
      run: |
        echo "NPM_TARGET=${{ github.event.inputs.npm_target || env.DEFAULT_NPM_TARGET }}" >> $GITHUB_ENV
        echo "PODMAN_PROVIDER=${{ github.event.inputs.podman_provider || env.DEFAULT_PODMAN_PROVIDER }}" >> $GITHUB_ENV
        echo "PODMAN_URL=${{ github.event.inputs.podman_remote_url || env.DEFAULT_URL }}" >> $GITHUB_ENV
        echo "ENV_VARS=${{ github.event.inputs.env_vars || env.DEFAULT_ENV_VARS }},IMAGE_SIZE=${{ github.event.inputs.image_size || env.DEFAULT_IMAGE_SIZE}}" >> $GITHUB_ENV
        echo "${{ github.event.inputs.host_params || env.DEFAULT_HOST_PARAMS }}" | awk -F ',' \
        '{for (i=1; i<=NF; i++) {split($i, kv, "="); print "HOST_PARAMS_"kv[1]"="kv[2]}}' >> $GITHUB_ENV
        echo "${{ github.event.inputs.podman_options || env.DEFAULT_PODMAN_OPTIONS }}" | awk -F ',' \
         '{for (i=1; i<=NF; i++) {split($i, kv, "="); print "PODMAN_"kv[1]"="kv[2]}}' >> $GITHUB_ENV
        echo "${{ github.event.inputs.pd_repo_options || env.DEFAULT_PD_REPO_OPTIONS }}" | awk -F ',' \
        '{for (i=1; i<=NF; i++) {split($i, kv, "="); print "PD_"kv[1]"="kv[2]}}' >> $GITHUB_ENV
        echo "${{ github.event.inputs.images_version || env.DEFAULT_IMAGES_VERSIONS }}" | awk -F ',' \
         '{for (i=1; i<=NF; i++) {split($i, kv, "="); print "PDE2E_"kv[1]"="kv[2]}}' >> $GITHUB_ENV

        # For mapt_params, use repo variables directly if input is empty
        if [ -n "${{ github.event.inputs.mapt_params }}" ]; then
          mapt_params="${{ github.event.inputs.mapt_params }}"
        else
          mapt_params="IMAGE=${{ vars.MAPT_IMAGE }};VERSION_TAG=${{ vars.MAPT_VERSION_TAG }};CPUS=${{ vars.MAPT_CPUS }};MEMORY=${{ vars.MAPT_MEMORY }};EXCLUDED_REGIONS=\"${{ vars.MAPT_EXCLUDED_REGIONS }}\""
        fi
        echo "$mapt_params" | awk -F ';' '{for (i=1; i<=NF; i++) {split($i, kv, "="); print "MAPT_"kv[1]"="kv[2]}}' >> $GITHUB_ENV

    - name: Create instance
      uses: podman-desktop/e2e/.github/actions/create-instance@main
      with:
        mapt-image: ${{ env.MAPT_IMAGE || '' }}
        mapt-version: ${{ env.MAPT_VERSION_TAG || '' }}
        windows-version: ${{ matrix.windows-version }}
        windows-featurepack: ${{ matrix.windows-featurepack }}
        cpus: ${{ env.MAPT_CPUS || '' }}
        memory: ${{ env.MAPT_MEMORY || '' }}
        excluded-regions: ${{ env.MAPT_EXCLUDED_REGIONS || '' }}
        arm-tenant-id: ${{ secrets.ARM_TENANT_ID }}
        arm-subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        arm-client-id: ${{ secrets.ARM_CLIENT_ID }}
        arm-client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

    - name: Check instance system info
      uses: podman-desktop/e2e/.github/actions/instance-system-info@main

    - name: Emulate X session
      uses: podman-desktop/e2e/.github/actions/emulate-x-session@main

    - name: Setup dependencies and build Podman Desktop locally
      uses: podman-desktop/e2e/.github/actions/build-podman-desktop@main
      with:
        fork: ${{ env.PD_FORK }}
        branch: ${{ env.PD_BRANCH }}
        env-vars: ${{ env.ENV_VARS }}

    - name: Download Podman nightly, do not initialize
      uses: podman-desktop/e2e/.github/actions/download-podman-nightly@main
      with:
        podman-image-tag: ${{ env.PDE2E_PODMAN }}
        podman-download-url: ${{ env.PODMAN_URL }}

    - name: Run Podman Desktop Playwright E2E tests
      uses: podman-desktop/e2e/.github/actions/run-playwright-test@main
      with:
        pde2e-runner-tag: ${{ env.PDE2E_RUNNER }}
        fork-repo: ${{ env.PD_FORK }}
        branch-name: ${{ env.PD_BRANCH }}
        npm-target: ${{ env.NPM_TARGET }}
        podman-init: ${{ env.PODMAN_INIT }}
        rootful: ${{ env.PODMAN_ROOTFUL }}
        podman-start: ${{ env.PODMAN_START }}
        user-networking: ${{ env.PODMAN_NETWORKING }}
        podman-provider: ${{ env.PODMAN_PROVIDER }}
        env-vars: ${{ env.ENV_VARS }}
        script-path: 'stress_test_ui.ps1'
        ci-bot-token: ${{ secrets.PODMANDESKTOP_CI_BOT_TOKEN }}

    - name: Destroy instance
      if: always()
      uses: podman-desktop/e2e/.github/actions/destroy-instance@main
      with:
        mapt-image: ${{ env.MAPT_IMAGE || '' }}
        mapt-version: ${{ env.MAPT_VERSION_TAG || '' }}
        arm-tenant-id: ${{ secrets.ARM_TENANT_ID }}
        arm-subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        arm-client-id: ${{ secrets.ARM_CLIENT_ID }}
        arm-client-secret: ${{ secrets.ARM_CLIENT_SECRET }}

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v4
      if: always() # always run even if the previous step fails
      with:
        fail_on_failure: true
        include_passed: true
        detailed_summary: true
        annotate_only: true
        require_tests:  true
        report_paths: '**/*results.xml'

    - name: Upload test artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: results-e2e-${{ matrix.windows-version }}-debug
        path: |
          results/*
